name: planit_schedule_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  animated_background: ^2.0.0
  toastification: ^2.3.0
  curved_navigation_bar: ^1.0.6
  dash_chat_2: ^0.0.21
  table_calendar: ^3.1.2
  google_generative_ai: ^0.4.6
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  audioplayers: ^6.1.0
  timeline_tile: ^2.0.0
  connectivity_plus: ^6.0.5
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.8.0
  geolocator: ^13.0.1
  flutter_link_previewer: ^3.2.2
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  animations: ^2.0.11
  google_fonts: ^6.2.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  file_picker: ^8.1.4
  uuid: ^4.5.1
  google_places_flutter: ^2.0.9
  chrono: ^0.1.0
  fl_chart: ^0.65.0
  string_similarity: ^2.1.1
  permission_handler: ^11.3.1
  animated_emoji: ^3.1.0
  webview_flutter: ^4.10.0
  photo_view: ^0.14.0
  syncfusion_flutter_pdfviewer: ^27.1.56
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.4
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.1
  flutter_google_maps_webservices: ^1.1.1
  shake: ^3.0.0
  


# dependency_overrides:
#   dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/icon/icon.png
    - assets/images/
    - assets/lotties/
    - assets/musics/
    - assets/weather_icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Bold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package